Exception in thread "main" java.lang.RuntimeException
	at com.course.io.stream.standartIO.Driver.test(Driver.java:19)
	at com.course.io.stream.standartIO.Driver.main(Driver.java:15)
